### ISSUE TITLE
compilation error of utils.cpp 

### ISSUE THREAD

**Issue by maarten-k** [Illumina/agg#17]
I tried to compile the latest agg master and building fails with: 

> 
> 
> 'utils.cpp:12:12: error: no viable conversion from returned value of type 'ifstream' (aka 'basic_ifstream<char>') to function return type 'bool'
>     return ifile;
>            ^~~~~

I tested using 
- gcc version 6.1.0 (linux centos 6) 
-  Apple LLVM version 7.3.0 (clang-703.0.31)
( x86_64-apple-darwin15.6.0) 

and occurred on both systems.

**Comment by maarten-k** [comment]
Seems that commit d903f2190e6a3e7b94ad27b7f919f36e080f1e7a solved the problem. Thanks @jaredo  for the rapid responds

**Comment by jaredo** [comment]
Great.
