### ISSUE TITLE
Genotype arbitary positions such as somatic variants.

### ISSUE THREAD

**Issue by johnpeden** [Illumina/agg#2]
Generate a bcf file from a VCF of a set of arbitrary variants that may consist entirely of positions that are non-variant in the populations processed by Agg. 

The resulting output file should, or have the option to, only contain the queried positions. 

Suggested command-line 
  agg genotype -G somatic_sites.vcf.gz chunk0.bcf chunk1.bcf

**Comment by jaredo** [comment]
After some thought, I don't think this should be implemented. My concern is that genotyping some arbitrary variant that has not been seen in any sample will give the user a false sense of security that samples are homref.

You can imagine a situation where an aligner/caller are not sensitive to a particular indel, but there is still coverage in the region. This might lead agg to assert false homref calls for the variant.

Users can always check the depth in the region of interest and make a judgement call.
