### ISSUE TITLE
negative DP values

### ISSUE THREAD

**Issue by saralpulit** [Illumina/agg#4]
Hi Jared,

I've aggregated/merged gVCF files from ~4,500 samples. 1,935 samples were sequenced on the HiSeq 2000 (and thus called with an older version of the Isaac pipeline). The rest were sequenced on the HiSeq X and called with a newer version of the pipeline.

I noticed in calculating average depth by sample and site the indels seemed to be dramatically over-covered. Oddly, the average sample depth was as expected (~35x) for the HiSeq 2000 samples but >> 80,000x (yes, that's right) for the HiSeq X samples. I've narrowed it down to gigantic negative DP values that I am seeing in the VCFs post aggregration that I think VCFtools is then reading as positive values. See screenshot for an example. I think this could be a bug in the agg tool? Something weird happening for when DP (or DPI?) gets merged together?

I'll keep digging into the data, but for now it seems that the data is fine going into agg, and it's the merged "DP" at the end that seems to be incorrect. I still haven't figured out why all seems to be fine for the HiSeq 2000 samples but not for the newer samples. The *.genome.vcf.gz files we got for all sets of samples look to be identically formatted.

Any insights?

Thanks,
Sara

<img width="1012" alt="screen shot 2016-03-03 at 13 45 39" src="https://cloud.githubusercontent.com/assets/15264717/13496768/5fa55918-e152-11e5-8ce1-b911d17b86f6.png">

**Comment by jaredo** [comment]
Hi Sara,

I think this is a bug I that just recently fixed. It relates to overlapping variants with missing values (the BCF symbolic missing value is a large negative integer which I failed to catch in this case). If you pull from the master branch, recompile and then run `agg genotype` again (no need to re-ingest). The problem should no longer occur. 

If you could check this in a small region first via:

```
agg genotype -r chr1:0-1000000 chunk0 chunk1 -Ob -o test.bcf
```

to make sure it is fixed and let me know, that would be great!

Jared

**Comment by saralpulit** [comment]
Hi Jared,

Yup! That's seems to have fixed the problem. DP at the site is now ~56,000, so much more reasonable.

Thanks!

Sara

**Comment by jaredo** [comment]
Great news. 

It might worth considering aggregating the different bioinformatics pipelines separately and then performing some sort of meta-analysis. Depends on your application.
