### ISSUE TITLE
Upon ingestion step 1, discard variants where REF allele doesn't match the reference

### ISSUE THREAD

**Issue by katherinesmith** [Illumina/agg#5]
Variants where the REF allele doesn't match the reference sequence cause `bcftools norm`, and hence the first step of agg ingestion, to fail.

`bcftools norm --check-ref` can be used to warn about such variants and gracefully exclude them or set them from the reference sequence: `bcftools norm --check-ref -wx -f $reference` or `bcftools norm --check-ref -ws -f $reference` in bcftools 1.3.

It would be great if the agg ingestion step could (perhaps optionally) call `bcftools norm --check-ref` so that a small number of problem variants doesn't prevent ingestion from completing.

**Comment by katherinesmith** [comment]
Here's an example:

```Reference allele mismatch at 9:27211458 .. REF_SEQ:'AG' vs VCF:’AA'```

**Comment by jaredo** [comment]
I have added `--ignore-non-matching-ref` to both `agg ingest` and `make_chunk.py` in 75ac6b55ac535c9ccdb1af13c5cb66df0a4876de.

This will mimic the behaviour of `bcftools norm -wx`. That is, sites where REF does not match the reference will be dropped.

**Comment by katherinesmith** [comment]
Brilliant, thanks for adding this feature this so quickly! I've tested it on a single problematic gVCF, which now completes ingestion successfully.

**Comment by jaredo** [comment]
Great!
