### ISSUE TITLE
agg runs forever

### ISSUE THREAD

**Issue by TsviyaOlender** [Illumina/agg#9]
We are trying to combine several cohorts, each contains ~1000 samples. While we could easily create chunks, without any errors, the agg genotypes step run forever for some of the chromosomes. Different chromosome in every cohort.

**Comment by jaredo** [comment]
Thanks for the bug report. This is almost certainly the same problem being discussed in #7. We understand why the problem occurs in `agg genotype` but the real problem is something upstream in the ingestion process.

Could you take a look at the start of the .dpt/.bcf file for one of the problematic chromosomes?

eg.
```
bcftools view xxx.bcf -r chr1 -H -G | head
bcftools view xxx.dpt -r chr1 -H -G | head
```
and confirm that the first position in the .bcf file is less than the first position in the .dpt file (this is what causes the bug).

**Comment by TsviyaOlender** [comment]
Hi
Thanks for prompt answer.
Yes, I confirm that the first position in the .bcf file is less than the first position in the .dpt file.
Glad that this is the same bug.

Other than that I find agg to be a great tool. Looking forward hearing from you that you solved the bug…
Thanks
Tsviya




[chenc@molgen chunks]$ bcftools view chunk_kings_1.bcf -r chr9 -H -G |head
chr9    4490469 .       C       T       175     .       .
chr9    4490760 rs2229885,rs76972569    G       C       533     .       .
chr9    4490880 rs12002726      T       C       640     .       .
chr9    4490885 .       GC      G       696     .       .
chr9    4490885 rs142132122     G       GC      244     .       .
chr9    4490948 .       A       G       169     .       .
chr9    4490959 rs74907704      A       T       112     .       .
chr9    4544640 rs142903137     T       C       272     .       .
chr9    4544721 rs45518336      A       T       721     .       .
chr9    4544750 .       A       T       209     .       .
[chenc@molgen chunks]$ bcftools view chunk_kings_1.dpt -r chr9 -H -G |head
chr9    4490483 .       N       .       .       .       .
chr9    4490484 .       N       .       .       .       .
chr9    4490485 .       N       .       .       .       .
chr9    4490486 .       N       .       .       .       .
chr9    4490487 .       N       .       .       .       .
chr9    4490488 .       N       .       .       .       .
chr9    4490489 .       N       .       .       .       .
chr9    4490490 .       N       .       .       .       .
chr9    4490491 .       N       .       .       .       .
chr9    4490492 .       N       .       .       .       .

**Comment by jaredo** [comment]
Thanks. So my concern is that the SNP at `chr9:4490469` would not be genotyped correctly at non-ALT samples since there was no depth information stored ie. agg does not appear to have built the .dpt file correctly here. 

Would it be possible for you to send the me output of 
`bcftools view -r chr9 -H sample.genome.vcf.gz | head` for a sample that contains the `C/T` SNP at `chr9:4490469`? (Maybe via email). That would help me to try and understand what is causing this.

**Comment by TsviyaOlender** [comment]
There are five such samples. I am attaching the output of the command for all those samples.
Please let me know if there is anything more that can assist you.

Tsviya
________________________________

**Comment by jaredo** [comment]
Thanks - I think I see the problem. Will resolve this over the next few days.

**Comment by TsviyaOlender** [comment]
Thanks!!

**Comment by jaredo** [comment]
Is it possible that these GVCFs have been pre-processed in any way? It looks like the start of the chromosome is missing. Typically our GVCFs will start at position 1 of each chromosome. For example, chr9 on NA18278 looks like this:

```
$ bcftools view -r chr9 -H NA12878_S1.genome.vcf.gz | head
chr9	1	.	N	.	.	LowGQX	END=10045;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	.:.:0:0
chr9	10046	.	C	.	.	LowGQX	END=10051;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	0/0:3:1:0
chr9	10052	rs370278117	C	T	8	LowGQXHetSNP	SNVSB=0;SNVHPOL=3;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant	GT:GQ:GQX:DP:DPF:AD	0/1:34:5:3:1:1,2
chr9	10053	.	A	.	.	LowGQX	END=10075;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	0/0:7:3:1
chr9	10075	rs373098387	C	CT	92	PASS	CIGAR=1M1I;RU=T;REFREP=0;IDREP=1;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant	GT:GQ:GQX:DPI:AD	0/1:49:6:6:2,3
chr9	10076	.	A	.	.	LowGQX	END=10085;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	0/0:12:5:1
chr9	10086	.	C	.	.	LowGQX;HighDPFRatio	END=10098;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	0/0:5:2:5
chr9	10098	rs563097040	C	CT	86	PASS	CIGAR=1M1I;RU=T;REFREP=0;IDREP=1;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant	GT:GQ:GQX:DPI:AD	0/1:105:7:7:4,3
chr9	10099	.	A	.	.	LowGQX;HighDPFRatio	END=10121;BLOCKAVG_min30p3a	GT:GQX:DP:DPF	0/0:3:1:5
chr9	10122	.	T	.	.	LowGQX;HighDPFRatio	.	GT:GQX:DP:DPF	.:.:0:7
```

**Comment by TsviyaOlender** [comment]
Yes, the files are processed. We recieved from our collaborators gvcf files that contain about 4Mb of the human genome each. The regions of interest were extracted from a whole human genome gvcf files using vcftools with the option --bed coordinates.bed
That is why the files dont start at 1. I hope that agg is ment to work also with such files...


נשלח ממכשיר ה-Samsung שלי


-------- הודעה מקורית --------
מאת: jaredo <notifications@github.com>
תאריך: 06/06/2016 19:59 (GMT+02:00)
אל: Illumina/agg <agg@noreply.github.com>
עותק: Tsviya Olender <tsviya.olender@weizmann.ac.il>, Author <author@noreply.github.com>
נושא: Re: [Illumina/agg] agg runs forever (#9)


Is it possible that these GVCFs have been pre-processed in any way? It looks like the start of the chromosome is missing. Typically our GVCFs will start at position 1 of each chromosome. For example, chr9 on NA18278 looks like this:

$ bcftools view -r chr9 -H NA12878_S1.genome.vcf.gz | head
chr9    1   .   N   .   .   LowGQX  END=10045;BLOCKAVG_min30p3a GT:GQX:DP:DPF   .:.:0:0
chr9    10046   .   C   .   .   LowGQX  END=10051;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:3:1:0
chr9    10052   rs370278117 C   T   8   LowGQXHetSNP    SNVSB=0;SNVHPOL=3;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant  GT:GQ:GQX:DP:DPF:AD 0/1:34:5:3:1:1,2
chr9    10053   .   A   .   .   LowGQX  END=10075;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:7:3:1
chr9    10075   rs373098387 C   CT  92  PASS    CIGAR=1M1I;RU=T;REFREP=0;IDREP=1;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant   GT:GQ:GQX:DPI:AD    0/1:49:6:6:2,3
chr9    10076   .   A   .   .   LowGQX  END=10085;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:12:5:1
chr9    10086   .   C   .   .   LowGQX;HighDPFRatio END=10098;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:5:2:5
chr9    10098   rs563097040 C   CT  86  PASS    CIGAR=1M1I;RU=T;REFREP=0;IDREP=1;CSQT=1|DDX11L5|NR_051986.1|upstream_gene_variant,1|WASH1|XM_005251335.1|downstream_gene_variant;CSQR=1|ENSR00001298704|regulatory_region_variant   GT:GQ:GQX:DPI:AD    0/1:105:7:7:4,3
chr9    10099   .   A   .   .   LowGQX;HighDPFRatio END=10121;BLOCKAVG_min30p3a GT:GQX:DP:DPF   0/0:3:1:5
chr9    10122   .   T   .   .   LowGQX;HighDPFRatio .   GT:GQX:DP:DPF   .:.:0:7

**Comment by jaredo** [comment]
Ah. This tool is really designed to run on whole-genome data although it can probably be subverted for your use-case. If you find the maximum start position in your dpt files and query starting from that position, the problem should not occur. 

eg. In your example you could do:
```
agg genotype -r  chr9:4490483-end chunk*.bcf -Ob -o example.bcf
```
I can't fully guarantee this is working properly though!

I will add an appropriate error message to stop the problem from occurring as well.

**Comment by TsviyaOlender** [comment]
Thanks for the advice, but it isn't working:

[chenc@molgen Updated_analysis]$ ~chenc/agg-master/agg genotype -r chr9:4490483-end chunks/chunk_kings_*.bcf -Ob -o example.bcf
chunks/chunk_kings_1.bcf chunks/chunk_kings_2.bcf
n_threads = 0
[synced_bcf_reader.c:917 _regions_init_string] Could not parse the region(s): chr9:4490483-end
ERROR: problem setting regions
Exiting...


So, what about Exome data? Didn't you thought to include such type of experiments as well?
Would you conciser to expand agg to work on a subset of the genome?




________________________________

**Comment by jaredo** [comment]
Replace "end" with the the last position of your genomic region of interest :)

**Comment by TsviyaOlender** [comment]
Thanks. I will give it a try.
So, the end can be constant number and not depend in what was called in the gvcf?

________________________________

**Comment by jaredo** [comment]
As long as it is greater than start it should be fine. Even if it is larger than the end of the vcf, the software will reach the end of the file and terminate.

**Comment by TsviyaOlender** [comment]
Thanks


נשלח ממכשיר ה-Samsung שלי


-------- הודעה מקורית --------
מאת: jaredo <notifications@github.com>
תאריך: 06/06/2016 22:18 (GMT+02:00)
אל: Illumina/agg <agg@noreply.github.com>
עותק: Tsviya Olender <tsviya.olender@weizmann.ac.il>, Author <author@noreply.github.com>
נושא: Re: [Illumina/agg] agg runs forever (#9)


As long as it is greater than start it should be fine. Even if it is larger than the end of the vcf, the software will reach the end of the file and terminate.

**Comment by jaredo** [comment]
>So, what about Exome data? Didn't you thought to include such type of experiments as well? Would you conciser to expand agg to work on a subset of the genome?

I could look at adding exome/subset functionality if this becomes a frequent request, but this is not a priority. Please keep in mind this is just a small piece of code I have put online in the hope that it would be useful, it is not an officially supported commercial product.

**Comment by TsviyaOlender** [comment]
Hi
I understand.
Thanks for looking into it.

Tsviya
________________________________
